package com.app01.kfc.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_user.id
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_user.name
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_user.telephone
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_user.password
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_user.photo
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    private String photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_user.id
     *
     * @return the value of kfc_user.id
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_user.id
     *
     * @param id the value for kfc_user.id
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_user.name
     *
     * @return the value of kfc_user.name
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_user.name
     *
     * @param name the value for kfc_user.name
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_user.telephone
     *
     * @return the value of kfc_user.telephone
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_user.telephone
     *
     * @param telephone the value for kfc_user.telephone
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_user.password
     *
     * @return the value of kfc_user.password
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_user.password
     *
     * @param password the value for kfc_user.password
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_user.photo
     *
     * @return the value of kfc_user.photo
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_user.photo
     *
     * @param photo the value for kfc_user.photo
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }
}