package com.app01.kfc.mapper;

import com.app01.kfc.bean.UserRole;
import com.app01.kfc.bean.UserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kfc_user_role
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    long countByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kfc_user_role
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    int deleteByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kfc_user_role
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kfc_user_role
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kfc_user_role
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kfc_user_role
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    List<UserRole> selectByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kfc_user_role
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    UserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kfc_user_role
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kfc_user_role
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kfc_user_role
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kfc_user_role
     *
     * @mbg.generated Mon May 20 10:07:27 CST 2019
     */
    int updateByPrimaryKey(UserRole record);
}